### ISSUE TITLE
Addition to the list

### ISSUE THREAD

**Issue by hagarelsayed** [SaraEl-Metwally/Learn_Bioinformatics#1]
Dear Dr Sara, 

Thanks truly for providing such combo dose of Bioinformatics online MOOCs and roadmaps. There are two courses that I stumbled upon that I think would be of a great benefit to be added to your list. 

1. [DIY Transcriptomics](https://diytranscriptomics.com/)
As the name implies, it is a hybrid course covering easy to follow practices for bulk and single cell RNA-seq data analysis, with a primary focus on empowering students to be independent in the use of lightweight and open-source software and the R/bioconductor environment, with application on real datasets.
2. [Introduction to Bioinformatics and Computational Biology](https://liulab-dfci.github.io/bioinfo-combio/scrna2.html#scrna-seq-dimension-reduction)
This one is course providing the same material for STAT115/215, BIO/BST282 at Harvard University. What is most interesting about the course, in addition to its detailed flow through all types of bioinformatics techniques and flavors, is the covering for the Cancer immunotherapy module in a very informative way. 

Hope you can check these two sources and add them to your list if you found them interesting as well. 

Thanks,

**Comment by hagarelsayed** [comment]
I apologize, I just noticed that the second course is already added, so you may just consider checking the first one only. 
Thanks,

**Comment by SaraEl-Metwally** [comment]
Thank you very much Dr. Hagar. 
I will update the materials according to your suggestion.
